spring:
  datasource:
    url: jdbc:mysql://47.104.92.214:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      validation-query: SELECT 1
      validation-query-timeout: 2000
  ####找不到处理器直接抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
  ####是否为工程中的资源文件建立映射
  resources:
    add-mappings: false
  ###邮箱配置
  mail:
    host: smtp.qq.com
    port: 25
    username: 847118663@qq.com
    password: ulhsgvgqsyiibeje
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  ###Redis
  redis:
    host: 47.104.92.214
    port: 6379
    timeout: 1000
    password: root
    jedis:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 2
        max-wait: 100
  ###RabbitMQ
  rabbitmq:
    host: 47.104.92.214
    port: 5672
    username: root
    password: root
    virtual-host: blog
mybatis:
  ###数据库模型对象
  type-aliases-package: com.zzx.model.pojo
  mapper-locations: mapper/*.xml
  ###打印sql
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

###是否启用swagger
swagger:
  enable: true

logging:
  level:
    org.springframework.security: info
    root: info
  path: /root/springboot-blog






### jwt
jwt:
  ###过期时间 s数432000 5天
  time: 432000
  ###安全密钥
  secret: "BlogSecret"
  ###token前缀
  prefix: "Bearer "
  ###http头key
  header: "Authorization"

###图片上传配置
upload:
  #静态资源对外暴露的访问路径 一个* 代表只匹配该路径下的一级子路径
  staticAccessPath: /img/*
  #文件上传目录
  uploadFolder: /root/blog
  #文件夹层数
  layerCount: 2
  #文件夹内单位数
  folderSize: 16

###站点介绍
site:
  introduction: "我的博客"

server:
  port: 8888
  servlet:
    context-path: /api